apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubtest
  labels:
    app: emp_directory
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: Node
    spec:
      containers:
      - name: kubtest
        image: "markjeffery/kubtest:release-master"
        ports:
        - containerPort: 5010
        imagePullPolicy: Always
        env:
        - name: "APPDYNAMICS_CONTROLLER_HOST_NAME"
          value: "192.168.99.1"
        - name: "APPDYNAMICS_CONTROLLER_PORT"
          value: "8090"
        - name: "APPDYNAMICS_AGENT_ACCOUNT_NAME"
          value: "customer1"
        - name: "APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
          value:  "8d59389c-2bb9-4fc1-b495-90016f453d8c"
        - name: "APPDYNAMICS_AGENT_APPLICATION_NAME"
          value: "kubernetes"
        - name: "APPDYNAMICS_AGENT_TIER_NAME"
          value: "Node"
        - name: "EXTERNAL_WEB_SERVICE"
          value: "http://192.168.99.1:63958/MyAccounts/0"
        lifecycle:
          preStop:
            exec:
              command: ["/unregister.sh","unregister"]
