apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubtest
  labels:
    app: emp_directory
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: Node
    spec:
      containers:
      - name: kubtest
        image: "markjeffery/kubtest:release-master"
        ports:
        - containerPort: 5010
        imagePullPolicy: Always
        env:
        - name: "APPDYNAMICS_CONTROLLER_HOST_NAME"
          value: "se-demo-uk.demo.appdynamics.com"
        - name: "APPDYNAMICS_CONTROLLER_PORT"
          value: "8090"
        - name: "APPDYNAMICS_AGENT_ACCOUNT_NAME"
          value: "customer1"
        - name: "APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
          value:  "322e0fe1-11b0-4d5a-9a01-e674c656e089"
        - name: "APPDYNAMICS_AGENT_APPLICATION_NAME"
          value: "kubernetes"
        - name: "APPDYNAMICS_AGENT_TIER_NAME"
          value: "Node"
        - name: "EXTERNAL_WEB_SERVICE"
          value: "http://10.0.1.51:62400/MyAccounts/0"
        lifecycle:
          preStop:
            exec:
              command: ["/unregister.sh","unregister"]
